# Four-caller alternative-splicing quantification workflow for TCASIA.

from pathlib import Path
import sys

from snakemake.utils import min_version

min_version("7.0.0")
configfile: "config/config.yml"

LIB_DIR = Path(workflow.basedir).resolve().parent / "lib"
sys.path.insert(0, str(LIB_DIR))
from tcasia_config import (
    load_samples,
    majiq_strandness,
    normalize_strandness,
    require_config,
    salmon_library_type,
)

require_config(
    config,
    "samples",
    "output_dir",
    "bam_dir",
    "ref",
    "GFF",
    "MAJIQ_license",
    "suppa2_events",
    "SALMON_INDEX",
    "read_len",
    "strandness",
)

SAMPLE_TABLE = load_samples(config["samples"])
SAMPLES = list(SAMPLE_TABLE)
STRANDNESS = normalize_strandness(config["strandness"])
RMATS_LIBRARY_TYPE = STRANDNESS
SALMON_LIBRARY_TYPE = salmon_library_type(STRANDNESS)
MAJIQ_STRANDNESS = majiq_strandness(STRANDNESS)

OUTPUT_DIR = Path(config["output_dir"]).expanduser().resolve()
BAM_DIR = Path(config["bam_dir"]).expanduser().resolve()
LOG_DIR = OUTPUT_DIR / "logs"
THREADS = config.get("threads", {})

SAMPLE_FASTQ_1 = lambda wildcards: SAMPLE_TABLE[wildcards.sample]["fastq_1"]
SAMPLE_FASTQ_2 = lambda wildcards: SAMPLE_TABLE[wildcards.sample]["fastq_2"]
SAMPLE_BAM = lambda wildcards: str(
    BAM_DIR / wildcards.sample / f"{wildcards.sample}_Aligned.sortedByCoord.out.bam"
)


include: "rules/snakefile_majiq"
include: "rules/snakefile_rmats"
include: "rules/snakefile_suppa2"
include: "rules/snakefile_spladder"


rule all:
    input:
        expand(str(OUTPUT_DIR / "{sample}" / "majiq" / "{sample}.voila.tsv"), sample=SAMPLES),
        expand(str(OUTPUT_DIR / "{sample}" / "majiq" / "modulized"), sample=SAMPLES),
        expand(str(OUTPUT_DIR / "{sample}" / "rmats"), sample=SAMPLES),
        expand(str(OUTPUT_DIR / "{sample}" / "suppa2" / "{sample}_event.psi"), sample=SAMPLES),
        expand(str(OUTPUT_DIR / "{sample}" / "spladder"), sample=SAMPLES),
