# Snakefile v.0.1
# ssh node3
# cd /data/home/zyh/project/AS-Pipeline/snakemake/align-workflow
# micromamba activate snakemake
# snakemake -s Snakefile --dag | dot -Tpdf > dag.pdf
# 先运行这一段更新时间戳: nohup snakemake -s Snakefile --cores 10 --use-conda --rerun-incomplete --touch --retries 3 >PRJNA498500.log 2>&1 &
# Run with: nohup snakemake -s Snakefile --cores 10 --use-conda --rerun-incomplete --retries 3  --keep-going >PRJNA498500.log 2>&1 &
# save pid: echo $! > run.PRJNA498500.pid




configfile: "config/config.yml"
cohort = config["cohort"]
root_DIR = config["root_DIR"]
bam_DIR = root_DIR+"/AS/"+cohort+"/aligned"
clean_DIR = root_DIR+"/"+cohort+"/fq_clean"
qc_DIR = root_DIR+"/"+cohort+"/qc"

import os
import glob

# 获取样本列表
def get_samples():
    return [os.path.splitext(os.path.basename(x))[0].rsplit('_',1)[0] for x in glob.glob(f"{root_DIR}/{cohort}/fq/*_1.fastq.gz")]

# 定义样本
samples = get_samples()



rule all:
    input:
        expand(bam_DIR+"/{sample}/{sample}_Aligned.sortedByCoord.out.bam.bai", sample=samples),
        expand(bam_DIR+"/{sample}/{sample}_counts.id.txt", sample=samples),
        expand(qc_DIR+"/{sample}_fastp.html", sample=samples)

rule fastp_qc:
    input:
        fq1=root_DIR+"/"+cohort+"/fq/{sample}_1.fastq.gz",
        fq2=root_DIR+"/"+cohort+"/fq/{sample}_2.fastq.gz"
    output:
        fq1=clean_DIR+"/{sample}_1.clean.fastq.gz",
        fq2=clean_DIR+"/{sample}_2.clean.fastq.gz",
        html=qc_DIR+"/{sample}_fastp.html",
        json=qc_DIR+"/{sample}_fastp.json"
    params:
        threads=config["fastp_threads"],
        min_length=config["fastp_min_length"],
        phred=config["fastp_phred"],
        unqualified_percent=config["fastp_unqualified_percent_limit"],
        n_base_limit=config["fastp_n_base_limit"],
        clean_dir=clean_DIR,
        qc_dir=qc_DIR
    log:
        "logs/{sample}_fastp.log"
    conda: "fastp"
    shell:
        """
        mkdir -p {params.clean_dir} {params.qc_dir}
        fastp \
            -i {input.fq1} -I {input.fq2} \
            -o {output.fq1} -O {output.fq2} \
            --html {output.html} \
            --json {output.json} \
            --length_required {params.min_length} \
            --qualified_quality_phred {params.phred} \
            --unqualified_percent_limit {params.unqualified_percent} \
            --n_base_limit {params.n_base_limit} \
            --thread {params.threads} \
            --detect_adapter_for_pe \
        > {log} 2>&1
        """

rule star_align:
    input:
        fq1=clean_DIR+"/{sample}_1.clean.fastq.gz",
        fq2=clean_DIR+"/{sample}_2.clean.fastq.gz"
    output:
        bam=bam_DIR+"/{sample}/{sample}_Aligned.out.bam"
    params:
        prefix=bam_DIR+"/{sample}/{sample}_",
        root_DIR = config["root_DIR"],
        cohort=config["cohort"],
        genomeDir=config["star_index_DIR"]  # 可根据需要添加其他STAR参数
    log:
        "logs/{sample}_star.log"
    conda: "ega"
    shell:
        """
        mkdir -p {params.root_DIR}/AS/{params.cohort}/aligned/{wildcards.sample}
        STAR --runThreadN 10 \
             --genomeDir {params.genomeDir} \
             --readFilesIn {input.fq1} {input.fq2} \
             --outFileNamePrefix {params.prefix} \
             --outSAMunmapped Within \
             --readFilesCommand zcat \
             --outFilterMismatchNmax 15 \
             --outSAMattributes All \
             --outStd Log \
             --limitBAMsortRAM 39050942993 \
             --outSAMtype BAM Unsorted \
             --outFilterIntronMotifs RemoveNoncanonical \
             --outSAMstrandField intronMotif \
             --twopassMode Basic \
             --quantMode GeneCounts \
        > {log} 2>&1
        """

rule sort_bam:
    input:
        bam=bam_DIR+"/{sample}/{sample}_Aligned.out.bam"
    params:
        cohort=config["cohort"],
        root_DIR = config["root_DIR"]
    output:
        sort_bam=bam_DIR+"/{sample}/{sample}_Aligned.sortedByCoord.out.bam"
    conda: "samtools1"
    shell:
        "samtools sort {input.bam} -@ 30 -o {output.sort_bam}"

rule index_bam:
    input:
        sort_bam=bam_DIR+"/{sample}/{sample}_Aligned.sortedByCoord.out.bam"
    output:
        bai=bam_DIR+"/{sample}/{sample}_Aligned.sortedByCoord.out.bam.bai"
    conda:"samtools1"
    params:
        cohort=config["cohort"],
        root_DIR = config["root_DIR"]
    shell:
        "samtools index {input.sort_bam} {output.bai}"

rule featureCounts:
    input:
        sort_bam=bam_DIR+"/{sample}/{sample}_Aligned.sortedByCoord.out.bam"
    output:
        counts=bam_DIR+"/{sample}/{sample}_counts.txt"
    conda:"subread"
    params:
        ref=config["ref"],
    shell:
        """
        featureCounts -T 40 -p -t exon \
        -g gene_id -a {params.ref} \
        -o {output.counts} \
        {input.sort_bam}
        """

rule getCounts:
    input:
        counts=bam_DIR+"/{sample}/{sample}_counts.txt"
    output:
        counts_tmp=bam_DIR+"/{sample}/{sample}_counts.id.tmp.txt"
    conda:"subread"
    shell:
        """
        cat {input.counts} | cut -f1,7- > {output.counts_tmp}
        """   
     
rule changecolumn:
    input:
        counts_tmp=bam_DIR+"/{sample}/{sample}_counts.id.tmp.txt"
    conda:"R4.4.3"
    output:
        counts_id=bam_DIR+"/{sample}/{sample}_counts.id.txt"
    script:
        'script/column.R'
