# RNA-seq quality-control and alignment workflow for TCASIA.

from pathlib import Path
import sys

from snakemake.utils import min_version

min_version("7.0.0")
configfile: "config/config.yml"

LIB_DIR = Path(workflow.basedir).resolve().parent / "lib"
sys.path.insert(0, str(LIB_DIR))
from tcasia_config import load_samples, normalize_strandness, require_config

require_config(config, "samples", "output_dir", "star_index_DIR", "ref", "strandness")
SAMPLE_TABLE = load_samples(config["samples"])
SAMPLES = list(SAMPLE_TABLE)
STRANDNESS = normalize_strandness(config["strandness"])

OUTPUT_DIR = Path(config["output_dir"]).expanduser().resolve()
CLEAN_DIR = OUTPUT_DIR / "clean_fastq"
QC_DIR = OUTPUT_DIR / "qc"
ALIGN_DIR = OUTPUT_DIR / "aligned"
LOG_DIR = OUTPUT_DIR / "logs"

THREADS = config.get("threads", {})
FASTP = config.get("fastp", {})
STAR = config.get("star", {})


rule all:
    input:
        expand(str(ALIGN_DIR / "{sample}" / "{sample}_Aligned.sortedByCoord.out.bam.bai"), sample=SAMPLES),
        expand(str(ALIGN_DIR / "{sample}" / "{sample}_featureCounts.txt"), sample=SAMPLES),
        expand(str(QC_DIR / "{sample}_fastp.html"), sample=SAMPLES),


rule fastp_qc:
    input:
        fq1=lambda wildcards: SAMPLE_TABLE[wildcards.sample]["fastq_1"],
        fq2=lambda wildcards: SAMPLE_TABLE[wildcards.sample]["fastq_2"],
    output:
        fq1=str(CLEAN_DIR / "{sample}_1.clean.fastq.gz"),
        fq2=str(CLEAN_DIR / "{sample}_2.clean.fastq.gz"),
        html=str(QC_DIR / "{sample}_fastp.html"),
        json=str(QC_DIR / "{sample}_fastp.json"),
    threads: int(THREADS.get("fastp", 8))
    params:
        min_length=int(FASTP.get("min_length", 36)),
        phred=int(FASTP.get("qualified_quality_phred", 20)),
        unqualified_percent=int(FASTP.get("unqualified_percent_limit", 40)),
        n_base_limit=int(FASTP.get("n_base_limit", 5)),
    log:
        str(LOG_DIR / "fastp" / "{sample}.log"),
    conda:
        "envs/fastp.yaml"
    shell:
        """
        mkdir -p "$(dirname {output.fq1:q})" "$(dirname {output.html:q})" "$(dirname {log:q})"
        fastp \
            -i {input.fq1:q} -I {input.fq2:q} \
            -o {output.fq1:q} -O {output.fq2:q} \
            --html {output.html:q} --json {output.json:q} \
            --length_required {params.min_length} \
            --qualified_quality_phred {params.phred} \
            --unqualified_percent_limit {params.unqualified_percent} \
            --n_base_limit {params.n_base_limit} \
            --thread {threads} --detect_adapter_for_pe \
            > {log:q} 2>&1
        """


rule star_align:
    input:
        fq1=str(CLEAN_DIR / "{sample}_1.clean.fastq.gz"),
        fq2=str(CLEAN_DIR / "{sample}_2.clean.fastq.gz"),
    output:
        bam=str(ALIGN_DIR / "{sample}" / "{sample}_Aligned.out.bam"),
    threads: int(THREADS.get("star", 10))
    params:
        prefix=lambda wildcards: str(ALIGN_DIR / wildcards.sample / f"{wildcards.sample}_"),
        genome_dir=config["star_index_DIR"],
        mismatch_max=int(STAR.get("out_filter_mismatch_nmax", 15)),
        bam_sort_ram=int(STAR.get("limit_bam_sort_ram", 39050942993)),
    log:
        str(LOG_DIR / "star" / "{sample}.log"),
    conda:
        "envs/ega.yaml"
    shell:
        """
        mkdir -p "$(dirname {output.bam:q})" "$(dirname {log:q})"
        STAR --runThreadN {threads} \
             --genomeDir {params.genome_dir:q} \
             --readFilesIn {input.fq1:q} {input.fq2:q} \
             --outFileNamePrefix {params.prefix:q} \
             --outSAMunmapped Within \
             --readFilesCommand zcat \
             --outFilterMismatchNmax {params.mismatch_max} \
             --outSAMattributes All \
             --outStd Log \
             --limitBAMsortRAM {params.bam_sort_ram} \
             --outSAMtype BAM Unsorted \
             --outFilterIntronMotifs RemoveNoncanonical \
             --outSAMstrandField intronMotif \
             --twopassMode Basic \
             --quantMode GeneCounts \
             > {log:q} 2>&1
        """


rule sort_bam:
    input:
        bam=str(ALIGN_DIR / "{sample}" / "{sample}_Aligned.out.bam"),
    output:
        bam=str(ALIGN_DIR / "{sample}" / "{sample}_Aligned.sortedByCoord.out.bam"),
    threads: int(THREADS.get("samtools_sort", 8))
    log:
        str(LOG_DIR / "samtools" / "{sample}.sort.log"),
    conda:
        "envs/samtools1.yaml"
    shell:
        """
        mkdir -p "$(dirname {log:q})"
        samtools sort -@ {threads} -o {output.bam:q} {input.bam:q} > {log:q} 2>&1
        """


rule index_bam:
    input:
        bam=str(ALIGN_DIR / "{sample}" / "{sample}_Aligned.sortedByCoord.out.bam"),
    output:
        bai=str(ALIGN_DIR / "{sample}" / "{sample}_Aligned.sortedByCoord.out.bam.bai"),
    threads: int(THREADS.get("samtools_index", 2))
    log:
        str(LOG_DIR / "samtools" / "{sample}.index.log"),
    conda:
        "envs/samtools1.yaml"
    shell:
        """
        mkdir -p "$(dirname {log:q})"
        samtools index -@ {threads} {input.bam:q} {output.bai:q} > {log:q} 2>&1
        """


rule featurecounts:
    input:
        bam=str(ALIGN_DIR / "{sample}" / "{sample}_Aligned.sortedByCoord.out.bam"),
    output:
        counts=str(ALIGN_DIR / "{sample}" / "{sample}_featureCounts.txt"),
    threads: int(THREADS.get("featurecounts", 8))
    params:
        annotation=config["ref"],
    log:
        str(LOG_DIR / "featurecounts" / "{sample}.log"),
    conda:
        "envs/subread.yaml"
    shell:
        """
        mkdir -p "$(dirname {log:q})"
        featureCounts -T {threads} -p -t exon -g gene_id \
            -a {params.annotation:q} -o {output.counts:q} {input.bam:q} \
            > {log:q} 2>&1
        """
