name: Pipeline checks

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true
      - name: Validate workflows
        shell: micromamba-shell {0}
        run: bash tests/run_tests.sh
